# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: TrianguloY
patreon: TrianguloY
ko_fi: TrianguloY
buy_me_a_coffee: TrianguloY
custom: [ 'https://www.paypal.com/biz/fund?id=W5CZR2YTVT5BQ', 'https://triangularapps.blogspot.com/p/support.html' ]
